# Generated by Django 5.1.6 on 2025-02-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='balance',
            new_name='amount',
        ),
    ]
